packages:
  - apps/game
  - apps/server
  - apps/workshop
  - packages/ui
  - packages/db
  - packages/api
  - packages/auth
  - packages/eslint-config-custom
  - packages/tailwind
  - packages/tsconfig